feat: qwerty keyboard and faster transaction reception and display
Kalapaja/kampela-firmware pull request #29
Opened 2024-06-07 19:13 UTC by Nyoxis

2024-10-22 19:02 UTC, Slesarew requested changes

2024-10-22 19:02 UTC, Slesarew commented on kampela_experiments_efm32pg23/patches/src/phrase.rs
This should be removed completely in favor of `mnemonic_external`

2024-10-22 19:02 UTC, Slesarew commented on kampela-system/src/flash_mnemonic.rs
> +#[cfg(not(feature = "std"))]
Not reviewing this file now, as other comments would probably mess this up a lot.

2024-10-23 06:01 UTC, Nyoxis commented on kampela-system/src/devices/flash.rs
> +    payload[ENCODED_LEN..].copy_from_slice(&pair.public.0);
Current version of firmware shows the public key as it starts if it has one. Made storing it to reduce visible loading time. At that moment there was no prospect on multiple keys, therefore i wasn't aware if that feature would be phased out in the future.

2024-11-19 19:18 UTC, Slesarew approved these changes

2024-11-19 19:18 UTC, merged